View(taxi)
taxi2 <- subset(taxi,taxi$RatecodeID < 90)
View(taxi2)
taxi3 <- subset(taxi,taxi$VendorID < 4)
View(taxi3)
taxi4 <- subset(taxi,taxi$fare_amount < 100)
View(taxi4)
taxi5 <- subset(taxi,taxi$trip_distance <15.01)
View(taxi5)
barplot(taxi2$RatecodeID,main = "Yellow Taxi Ratecode distribution Chart",xlab = "RatecodeID")
barplot(taxi3$VendorID,main = "Yellow Taxi VendorID distribution Chart",xlab = "VendorID")
hist(taxi4$fare_amount,main = "Yellow Taxi Fare Amount Histogram Chart",xlab = "Fare_Amount")
hist(taxi5$trip_distance,main = "Yellow Taxi Trip Distance Histogram Chart",xlab = "Trip_Distance")